/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diamondProxyContractSol from "./DiamondProxyContract.sol";
export type { diamondProxyContractSol };
import type * as erc20 from "./ERC20";
export type { erc20 };
