/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Facet__factory } from "./ERC20Facet__factory";
export { ERC20Internal__factory } from "./ERC20Internal__factory";
