/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IERC173 } from "./IERC173";
export type { IERC173Internal } from "./IERC173Internal";
export type { IERC20 } from "./IERC20";
export type { IERC20Internal } from "./IERC20Internal";
