/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondProxy__factory } from "./DiamondProxy__factory";
export { DiamondProxyContract__factory } from "./DiamondProxyContract__factory";
