/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./ERC20";
export type { erc20 };
export type { DiamondProxyContract } from "./DiamondProxyContract";
export * as factories from "./factories";
export { DiamondProxyContract__factory } from "./factories/DiamondProxyContract__factory";
export type { ERC20Facet } from "./ERC20/ERC20Facet";
export { ERC20Facet__factory } from "./factories/ERC20/ERC20Facet__factory";
export type { ERC20Internal } from "./ERC20/ERC20Internal";
export { ERC20Internal__factory } from "./factories/ERC20/ERC20Internal__factory";
