/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondProxy } from "./DiamondProxy";
export type { DiamondProxyContract } from "./DiamondProxyContract";
